{% set name = "pandablocks" %}
{% set version = "0.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandablocks-{{ version }}.tar.gz
  sha256: 82ac0f40e23f43f050475f8254960b9071e70469ae357947aac2a7aafa475248

build:
  number: 0
  noarch: python
  entry_points:
    - pandablocks = pandablocks.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=6.2
    - wheel
  run:
    - click
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - pandablocks
  commands:
    - pip check
    - pandablocks --help
    - pandablocks --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PandABlocks/PandABlocks-client
  summary: A Python client to control and data ports of the PandABlocks TCP server
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pandablocks.github.io/PandABlocks-client/master/index.html
  dev_url: https://github.com/PandABlocks/PandABlocks-client

extra:
  recipe-maintainers:
    - beenje
