{% set name = "pandablocks" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandablocks-{{ version }}.tar.gz
  sha256: 5d2dfe3d5e1d31266c67c69f9cdaa7d4472f1b2d803212f51aa18e52e4c10290

build:
  number: 0
  noarch: python
  entry_points:
    - pandablocks = pandablocks.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - numpy
    - python >=3.7
    - importlib-metadata <5.0

test:
  imports:
    - pandablocks
  commands:
    - pip check
    - pandablocks --help
  requires:
    - pip

about:
  home: https://github.com/PandABlocks/PandABlocks-client
  summary: A Python client to control and data ports of the PandABlocks TCP server
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pandablocks.github.io/PandABlocks-client/master/index.html
  dev_url: https://github.com/PandABlocks/PandABlocks-client

extra:
  recipe-maintainers:
    - beenje
