{% set name = "pandablocks" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandablocks-{{ version }}.tar.gz
  sha256: 3be30bb1ded0ab0c199a84feeeff85d4cc4303ef112d14f2b3cf9ccce557729d

build:
  number: 0
  noarch: python
  entry_points:
    - pandablocks = pandablocks.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=64
    - setuptools_scm >=6.2
    - wheel
  run:
    - click
    - numpy
    - python >=3.7

test:
  imports:
    - pandablocks
  commands:
    - pip check
    - pandablocks --help
    - pandablocks --version
  requires:
    - pip

about:
  home: https://github.com/PandABlocks/PandABlocks-client
  summary: A Python client to control and data ports of the PandABlocks TCP server
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pandablocks.github.io/PandABlocks-client/master/index.html
  dev_url: https://github.com/PandABlocks/PandABlocks-client

extra:
  recipe-maintainers:
    - beenje
