schema_version: 1

context:
  name: pandablocks
  version: 0.10.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pandablocks-${{ version }}.tar.gz
  sha256: 82ac0f40e23f43f050475f8254960b9071e70469ae357947aac2a7aafa475248

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pandablocks = pandablocks.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools_scm >=6.2
    - wheel
  run:
    - click
    - numpy
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pandablocks
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - pandablocks --help
      - pandablocks --version

about:
  summary: A Python client to control and data ports of the PandABlocks TCP server
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/PandABlocks/PandABlocks-client
  repository: https://github.com/PandABlocks/PandABlocks-client
  documentation: https://pandablocks.github.io/PandABlocks-client/master/index.html

extra:
  recipe-maintainers:
    - beenje
